"""Data profile report (``docs/data_profile.md``): row counts, null rates and basic
distributions for every table, plus a few business-level highlights."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import duckdb
import yaml

from carquery.contract import Column, SchemaContract
from carquery.datafiles import connect_views, table_files

TOP_VALUES = 6
MAX_CATEGORIES = 30
_NUMERIC = ("SMALLINT", "INTEGER", "BIGINT", "DOUBLE", "DECIMAL")

HIGHLIGHTS: list[tuple[str, str]] = [
    (
        "Units sold by fiscal year and powertrain (non-cancelled sales)",
        """
        SELECT d.fiscal_year_label AS fiscal_year, m.powertrain, count(*) AS units
        FROM fact_sales s
        JOIN dim_date d ON d.calendar_date = s.sale_date
        JOIN fact_production p USING (vin)
        JOIN dim_vehicle_model m USING (model_id)
        WHERE NOT s.is_cancelled
        GROUP BY ALL ORDER BY fiscal_year, powertrain
        """,
    ),
    (
        "Sales by type: units, average discount rate and net revenue (EUR)",
        """
        SELECT sale_type, count(*) AS units,
               round(avg(discount_amount / list_price), 4) AS avg_discount_rate,
               sum(net_price) AS net_revenue_eur
        FROM fact_sales WHERE NOT is_cancelled
        GROUP BY ALL ORDER BY units DESC
        """,
    ),
    (
        "Service visits by type",
        """
        SELECT visit_type, count(*) AS visits, round(avg(total_cost), 2) AS avg_cost_eur,
               round(avg(is_warranty::INT), 3) AS warranty_share
        FROM fact_service_visit GROUP BY ALL ORDER BY visits DESC
        """,
    ),
    (
        "Warranty claims by component category and status",
        """
        SELECT pt.component_category, w.claim_status, count(*) AS claims,
               sum(w.total_cost) AS total_cost_eur
        FROM fact_warranty_claim w JOIN dim_part pt USING (part_id)
        GROUP BY ALL ORDER BY component_category, claim_status
        """,
    ),
    (
        "Warranty claim reporting lag (received_date - claim_date)",
        """
        SELECT CASE WHEN received_date - claim_date <= 3 THEN '0-3 days'
                    WHEN received_date - claim_date <= 30 THEN '4-30 days'
                    ELSE '31+ days' END AS lag, count(*) AS claims
        FROM fact_warranty_claim GROUP BY ALL ORDER BY lag
        """,
    ),
]


def build_profile(data_root: Path, contract: SchemaContract) -> str:
    con = connect_views(data_root, contract)
    try:
        return _render(con, data_root, contract)
    finally:
        con.close()


def _render(con: duckdb.DuckDBPyConnection, data_root: Path, contract: SchemaContract) -> str:
    out = [
        "# Data profile",
        "",
        "<!-- Generated by `carq profile`. Do not edit by hand. -->",
        "",
    ]
    truth = data_root / "ground_truth.yaml"
    if truth.is_file():
        meta = yaml.safe_load(truth.read_text(encoding="utf-8"))
        ds, hist = meta.get("dataset", {}), meta.get("history", {})
        out += [
            f"Dataset: preset `{ds.get('preset')}`, seed {ds.get('seed')}, history "
            f"{hist.get('start')} to {hist.get('end')}.",
            "",
        ]
    out += [
        "Planted patterns and how to detect them are documented in "
        "`<data_root>/ground_truth.yaml` (generated with the data).",
        "",
        "## Tables",
        "",
        "| Table | Kind | Rows | Files | Columns |",
        "|---|---|--:|--:|--:|",
    ]
    counts = {}
    for name, table in contract.tables.items():
        files = table_files(data_root, name)
        counts[name] = _one(con, f"SELECT count(*) FROM {name}") if files else 0
        out.append(
            f"| `{name}` | {table.kind} | {counts[name]:,} | {len(files)} | {len(table.columns)} |"
        )
    out.append("")

    out += ["## Highlights", ""]
    for title, query in HIGHLIGHTS:
        out += [f"### {title}", "", *_markdown_table(con, query), ""]

    out += ["## Columns", ""]
    for name, table in contract.tables.items():
        if not counts[name]:
            continue
        out += [
            f"### `{name}`",
            "",
            "| Column | Type | Null % | Distinct | Summary |",
            "|---|---|--:|--:|---|",
        ]
        for column in table.columns:
            out.append(_column_row(con, name, column, counts[name]))
        out.append("")
    return "\n".join(out)


def _column_row(con: duckdb.DuckDBPyConnection, table: str, column: Column, rows: int) -> str:
    c = column.name
    nulls, distinct, low, high = con.execute(
        f"SELECT count(*) - count({c}), count(DISTINCT {c}), min({c}), max({c}) FROM {table}"
    ).fetchone()  # type: ignore[misc]
    null_pct = f"{100 * nulls / rows:.1f}" if rows else "-"
    if column.type.startswith(_NUMERIC):
        avg = _one(con, f"SELECT avg({c}) FROM {table}")
        summary = f"min {_fmt(low)} · mean {_fmt(avg)} · max {_fmt(high)}"
    elif column.type == "DATE":
        summary = f"{low} to {high}"
    elif distinct <= MAX_CATEGORIES:
        top = con.execute(
            f"SELECT {c}, count(*) AS n FROM {table} WHERE {c} IS NOT NULL "
            f"GROUP BY {c} ORDER BY n DESC, {c} LIMIT {TOP_VALUES}"
        ).fetchall()
        summary = ", ".join(f"{_fmt(v)} {100 * n / rows:.1f}%" for v, n in top)
        if distinct > TOP_VALUES:
            summary += ", …"
    else:
        summary = f"e.g. {low}"
    return f"| `{c}` | {column.type} | {null_pct} | {distinct:,} | {summary} |"


def _markdown_table(con: duckdb.DuckDBPyConnection, query: str) -> list[str]:
    try:
        cursor = con.execute(query)
    except duckdb.Error as exc:
        return [f"_not available: {exc}_"]
    names = [d[0] for d in cursor.description]
    lines = ["| " + " | ".join(names) + " |", "|" + "---|" * len(names)]
    lines += ["| " + " | ".join(_fmt(v) for v in row) + " |" for row in cursor.fetchall()]
    return lines


def _fmt(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, str):
        return value
    try:
        number = float(value)
    except (TypeError, ValueError):
        return str(value)
    sep = "," if abs(number) >= 10_000 else ""  # no separators in years like 2026
    if isinstance(value, int):
        return f"{value:{sep}}"
    return f"{number:{sep}.2f}" if abs(number) >= 1 or number == 0 else f"{number:.4f}"


def _one(con: duckdb.DuckDBPyConnection, query: str) -> Any:
    row = con.execute(query).fetchone()
    return row[0] if row else None
